// import * as angular from "angular";
// import * as _ from "lodash";
// import {Player} from "../lib/player";
// import IService = restangular.IService;
// import * as restangular from "restangular";
// import IQService = angular.IQService;
// import {Npc} from "../lib/npc";
// import IComponentOptions = angular.IComponentOptions;
/**
 * Created by user on 05.01.17.
 */


require('../lib/PlayerService');
require('../lib/NpcService');
require('./talkService');

var talkTpl = require('./talk.pug');


angular.module('app').component('talk',{
  bindings:{
    $router:'<'
  },
  template:talkTpl(),
  controller :TalkCtrl,
  controllerAs:'ctrl'
});

TalkCtrl.$inject = ['TalkService'];
function TalkCtrl(service)
{
    this.gameName = "Окно переговоров";

    var _this=this;
    _this.player=service.getPlayer();
    _this.npc=service.getNpc();
    _this.getHistory = service.getHistory;
    _this.getPlayerQuestions = service.getPlayerQuestions;
    _this.update = service.update;
    _this.getNpcAnswers = service.getNpcAnswers;
    _this.getTime = service.getTime;

    _this.$routerOnActivate = function() {
        service.init();
    };
    
    _this.notTheEnd  = function() {
            var r;
            r = true;
            if (service.isStatus('failure') || service.isStatus('success')) {
                r = false;
            }
            return r;
        }

    _this.checkColor=function () {
        var f;
        f = "";
        if (service.isStatus('failure')) {
            f = "failure";
        }
        if (service.isStatus('success')) {
            f = "success";
        }
        return f;
    };

    





};




// ---
// generated by coffee-script 1.9.2